export const resmessage = {
  validation_error: "validation-error",
  confirm_password_mismatch: "confirm-password-mismatch",
  login_successful: "User Login successful!",
  username_email_exists: "username-email-exists",
  user_added: "user added successfully!",
  record_added: "record-added",
  record_updated: "record-updated",
  record_deleted: "record-deleted",
  record_exists: "record-exists",
  record_not_found: "record-not-found",
  mongodb_validation_err: "mongodb-validation-error",
  something_wrong: "something-went-wrong",
  bad_credentials: "bad-credentials",
  un_authorized_access: "un-authorized-access",
  user_not_found: "user-not-found",
  new_password_generated: "new-password-generated",
  incorrect_password: "incorrect-password",
  password_changed: "password-changed",
  profile_pic_uploaded: "profile-pic-uploaded",
  adver_pic_uploaded: "adver-pic-uploaded",
  record_can_not_be_deleted: "record-can-not-be-deleted",
  coin_currency_not_available: "coin-currency-not-available",
  transaction_successful: "Transaction Successful!",
  transaction_faliure: "Transaction failed",
  drive_success: "Drive created successfully!",
  update_status_no_passanger: "Updated successfully! No new passanger found",
  update_status_found_passanger: "Updated successfully! new passanger found",
  driver_found: "Driver found successfully!",
  driver_not_found: "Driver not found please try again",
};

export const constants = {
  ACTIVE_DRIVERS: "Data/activeDrivers.json",
  DRIVERS: "Data/drivers.json",
  PASSANGERS: "Data/passangers.json",
  JOURNEY: "Data/journey.json",
};
